#!/usr/bin/env bash

# Require commit message
if [ -z "$1" ]; then
  echo "Error: Commit message required"
  exit 1
fi




# "git init" for the first time
git add -A
git commit -m "$1"

# "git remote add origin https://github.com/DenzelJohnson/catan.git" for the first time
git fetch origin
git rebase origin/main

# for the first time:
# git branch -m master main
# "git push --set-upstream origin main" for the first time
git push --force-with-lease origin main




# If a second argument is provided, treat it as a version tag
if [ -n "$2" ]; then
  TAG="$2"

  # Create annotated tag
  git tag -a "$TAG" -m "$1"

  # Push tag
  git push origin "$TAG"

  # Create GitHub release
  gh release create "$TAG" \
    --title "$TAG" \
    --notes "$1"
fi
