# SonarQube project configuration
sonar.projectKey=catan
sonar.sources=src/main/java
sonar.exclusions=**/visualize/catanatron/**,**/visualize/scraped_boards/**,**/visualize/*.png,**/visualize/*.json,**/visualize/*.txt,**/visualize/*.py,**/visualize/.venv/**

# Exclude all Python files and vlibraries
sonar.coverage.exclusions=**/visualize/**
