// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

/************************************************************/
/**
 * 
 */
public enum ActionType {
	/**
	 * 
	 */
	PASS,
	/**
	 * 
	 */
	BUILD_ROAD,
	/**
	 * 
	 */
	BUILD_SETTLEMENT,
	/**
	 * 
	 */
	BUILD_CITY;
}
