// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	public static int TILE_COUNT;
	/**
	 * 
	 */
	public static int NODE_COUNT;
	/**
	 * 
	 */
	public static int EDGE_COUNT;

	/**
	 * 
	 */
	public Board() {
	}

	/**
	 * 
	 */
	private void initEmptyState() {
	}

	/**
	 * 
	 */
	private void initNode0t053() {
	}

	/**
	 * 
	 */
	private void initTilesFromSetupArray() {
	}

	/**
	 * 
	 */
	private void populateNodeAdjacentTileIdsFromTiles() {
	}

	/**
	 * 
	 */
	private void buildingEdgesFromTilePerimetersAndAssignIds() {
	}

	/**
	 * 
	 */
	private void populateNodeNeighbourNodeIdsFromEdges() {
	}

	/**
	 * 
	 * @param nodeId 
	 * @param owner 
	 */
	public void placeSettlement(int nodeId, Player owner) {
	}

	/**
	 * 
	 * @param nodeId 
	 * @param owner 
	 */
	public void placeCity(int nodeId, Player owner) {
	}

	/**
	 * 
	 * @param edgeIndex 
	 * @param owner 
	 */
	public void placeRoad(int edgeIndex, Player owner) {
	}

	/**
	 * 
	 * @param ndoeId 
	 * @return 
	 */
	public boolean violatesDistanceRule(int ndoeId) {
	}

	/**
	 * 
	 * @param playerId 
	 * @return 
	 */
	public int computeLongestRoadForPlayer(int playerId) {
	}

	/**
	 * 
	 * @param playerId 
	 * @param nodeId 
	 * @param usedEdges 
	 * @return 
	 */
	public int dfsExtendFromNode(int playerId, int nodeId, boolean[] usedEdges) {
	}

	/**
	 * 
	 * @param nodeId 
	 * @return 
	 */
	public int[] getAdjecentEdgeIndicesForNode(int nodeId) {
	}

	/**
	 * 
	 * @param diceToken 
	 * @return 
	 */
	public ResourceType[] getResourceTypesForDiceToken(int diceToken) {
	}

	/**
	 * 
	 * @param tileId 
	 * @return 
	 */
	public TerrainTile[] getTile(int tileId) {
	}

	/**
	 * 
	 * @param nodeId 
	 * @return 
	 */
	public Node[] getNode(int nodeId) {
	}

	/**
	 * 
	 * @param nodeId 
	 * @return 
	 */
	public Building[] getBuilding(int nodeId) {
	}

	/**
	 * 
	 * @param edgeIndex 
	 * @return 
	 */
	public Road[] getRoad(int edgeIndex) {
	}

	/**
	 * 
	 * @param edgeIndex 
	 * @return 
	 */
	public Edge getEdge(int edgeIndex) {
	}

	/**
	 * 
	 * @param edgeIndex 
	 * @return 
	 */
	public boolean isRoadEmpty(int edgeIndex) {
	}

	/**
	 * 
	 * @param nodeId 
	 * @return 
	 */
	public boolean isNodeEmpty(int nodeId) {
	}
}
