// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

/************************************************************/
/**
 * 
 */
public class Building {
	/**
	 * 
	 */
	public int ownerPlayerId;
	/**
	 * 
	 */
	public int nodeId;
	/**
	 * 
	 */
	public BuildingKind kind;

	/**
	 * 
	 * @param ownerPlayerId 
	 * @param nodeId 
	 * @param kind 
	 */
	public Building(int ownerPlayerId, int nodeId, BuildingKind kind) {
	}
}
