// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

import CatanUML.Random;

/************************************************************/
/**
 * 
 */
public class ComputerPlayer extends Player {
	/**
	 * 
	 */
	public Random r;

	/**
	 * 
	 * @param playerId 
	 */
	public ComputerPlayer(int playerId) {
	}

	/**
	 * 
	 * @param board 
	 */
	public void turn(Board board) {
	}

	/**
	 * 
	 * @param board 
	 * @param isSecondSettlement 
	 * @return 
	 */
	public int placeRandomValidSettlement(Board board, boolean isSecondSettlement) {
	}

	/**
	 * 
	 * @param board 
	 * @param settlemendNodeId 
	 * @return 
	 */
	public int placeRandomValidRoad(Board board, int settlemendNodeId) {
	}
}
