// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	public int node1;
	/**
	 * 
	 */
	public int node2;
	/**
	 * 
	 */
	public int edgeIndex;

	/**
	 * 
	 * @param nodeA 
	 * @param nodeB 
	 * @param edgeIndex 
	 */
	public Edge(int nodeA, int nodeB, int edgeIndex) {
	}
}
