// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private static int TARGET_VICTORY_POINTS;
	/**
	 * 
	 */
	private static int MAX_ROUNDS;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private int startingIndex;
	/**
	 * 
	 */
	private int currentPlayerIndex;
	/**
	 * 
	 */
	private int rounds;
	/**
	 * 
	 */
	private boolean isWinner;
	/**
	 * 
	 */
	private Player winner;
	/**
	 * 
	 */
	private Player longestRoadHolder;

	/**
	 * 
	 * @param board 
	 * @param players 
	 */
	public Game(Board board, Player[] players) {
	}

	/**
	 * 
	 */
	public void startGame() {
	}

	/**
	 * 
	 */
	public void initBankCards() {
	}

	/**
	 * 
	 */
	public void determineStartingPlayer() {
	}

	/**
	 * 
	 */
	public void playFirstTwoRoundsSetup() {
	}

	/**
	 * 
	 */
	public void playMainGame() {
	}

	/**
	 * 
	 */
	public void checkWinner() {
	}

	/**
	 * 
	 * @return 
	 * @param roll 
	 * @param currentPlayerId 
	 */
	public String awardResourcesForAllPlayers(int roll, int currentPlayerId) {
	}

	/**
	 * 
	 * @return 
	 * @param playerId 
	 */
	private Player getPlayerId(int playerId) {
	}

	/**
	 * 
	 * @return 
	 * @param startIndex 
	 * @param stepsForward 
	 */
	private int getPlayerIndexClockwise(int startIndex, int stepsForward) {
	}

	/**
	 * 
	 * @return 
	 * @param startIndex 
	 * @param stepsBackward 
	 */
	private int getPlayerIndexCounterClockwise(int startIndex, int stepsBackward) {
	}

	/**
	 * 
	 * @return 
	 * @param p 
	 * @param roundNumber 
	 */
	private int placeInitialSettlementAndRoad(Player p, int roundNumber) {
	}

	/**
	 * 
	 * @param p 
	 * @param settlementNodeId 
	 */
	private void addStartingResourcesFromSecondSettlement(Player p, int settlementNodeId) {
	}

	/**
	 * 
	 * @param roundNumber 
	 * @param playerId 
	 * @param action 
	 */
	private void displayTurnSummary(int roundNumber, int playerId, String action) {
	}

	/**
	 * 
	 */
	private void udpateLongestRoadHolder() {
	}
}
