// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	public int nodeId;
	/**
	 * 
	 */
	public int[] neighbourNodeIds;
	/**
	 * 
	 */
	public int[] adjacentTileIds;

	/**
	 * 
	 * @param nodeId 
	 */
	public Node(int nodeId) {
	}
}
