// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

import CatanUML.Random;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int playerId;
	/**
	 * 
	 */
	private int[] resourceCounts;
	/**
	 * 
	 */
	private int[] buildingCounts;
	/**
	 * 
	 */
	private int roadsCount;
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private int longestRoadStreak;
	/**
	 * 
	 */
	private int turns;
	/**
	 * 
	 */
	private Random r;

	/**
	 * 
	 * @param playerId 
	 */
	public Player(int playerId) {
	}

	/**
	 * 
	 * @param board 
	 * @return 
	 */
	public TurnResult turn(Board board) {
	}

	/**
	 * 
	 * @return 
	 */
	public int diceRoll() {
	}

	/**
	 * 
	 * @param board 
	 * @param edgeIndex 
	 */
	public void buildRoad(Board board, int edgeIndex) {
	}

	/**
	 * 
	 * @param board 
	 * @param nodeId 
	 */
	public void buildSettlement(Board board, int nodeId) {
	}

	/**
	 * 
	 * @param board 
	 * @param nodeId 
	 */
	public void buildCity(Board board, int nodeId) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canAffordRoad() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canAffordCity() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canAffordSettlement() {
	}

	/**
	 * 
	 * @return 
	 * @param board 
	 */
	public int[] findValidRoadPlacements(Board board) {
	}

	/**
	 * 
	 * @return 
	 * @param board 
	 */
	public int[] findValidCityPlacements(int board) {
	}

	/**
	 * 
	 * @param board 
	 * @param edgeIndex 
	 * @return 
	 */
	public boolean isEdgeConnectedToMyRoad(Board board, int edgeIndex) {
	}

	/**
	 * 
	 * @param board 
	 * @param nodeId 
	 * @return 
	 */
	public boolean doesNodeHaveMyBuilding(Board board, int nodeId) {
	}

	/**
	 * 
	 * @param board 
	 * @param nodeId 
	 * @return 
	 */
	public boolean doesNodeTouchMyRoad(Board board, int nodeId) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getPlayerId() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getLongestRoadStreak() {
	}

	/**
	 * 
	 * @param amount 
	 */
	public void addVictoryPoints(int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public int getResourceCount(ResourceType type) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public boolean hasAtLeastXResources(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void addResource(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void spendResource(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public int getBuildingCount(BuildingKind type) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public boolean hasAtLeastXBuildings(BuildingKind type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void addBuilding(BuildingKind type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void spendBuilding(BuildingKind type, int amount) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRoadsCount() {
	}

	/**
	 * 
	 * @param amount 
	 * @return 
	 */
	public boolean hasAtLeastXRoads(int amount) {
	}

	/**
	 * 
	 * @param amount 
	 */
	public void addRoads(int amount) {
	}

	/**
	 * 
	 * @param amount 
	 */
	public void spendRoads(int amount) {
	}
}
