// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	public int ownerId;
	/**
	 * 
	 */
	public int edgeIndex;

	/**
	 * 
	 * @param ownerPlayerId 
	 * @param edgeIndex 
	 */
	public Road(int ownerPlayerId, int edgeIndex) {
	}
}
