// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

/************************************************************/
/**
 * 
 */
public class TerrainTile {
	/**
	 * 
	 */
	public int tileId;
	/**
	 * 
	 */
	public ResourceType resourceType;
	/**
	 * 
	 */
	public int diceToken;
	/**
	 * 
	 */
	public int[] cornerNodeIdsClockwise;

	/**
	 * 
	 * @param tileId 
	 * @param resourceType 
	 * @param diceToken 
	 * @param cornderNodeIdsClockwise 
	 */
	public TerrainTile(int tileId, ResourceType resourceType, int diceToken, int[] cornderNodeIdsClockwise) {
	}
}
