// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanUML.Part1;

/************************************************************/
/**
 * 
 */
public class TurnResult {
	/**
	 * 
	 */
	public ActionType actionType;
	/**
	 * 
	 */
	public int edgeIndex;
	/**
	 * 
	 */
	public int nodeId;
	/**
	 * 
	 */
	public String decisionSummary;

	/**
	 * 
	 * @param actionType 
	 * @param edgeIndex 
	 * @param nodeId 
	 * @param decisionSummary 
	 */
	private TurnResult(ActionType actionType, int edgeIndex, int nodeId, String decisionSummary) {
	}

	/**
	 * 
	 * @param summary 
	 * @return 
	 */
	public static TurnResult pass(String summary) {
	}

	/**
	 * 
	 * @param edgeIndex 
	 * @param summary 
	 * @return 
	 */
	public static TurnResult buildRoad(int edgeIndex, String summary) {
	}

	/**
	 * 
	 * @param nodeId 
	 * @param summary 
	 * @return 
	 */
	public static TurnResult buildSettlement(int nodeId, String summary) {
	}

	/**
	 * 
	 * @param nodeId 
	 * @param summary 
	 * @return 
	 */
	public static TurnResult buildCity(int nodeId, String summary) {
	}
}
